databaseType = "SqlServer"
id = "8b36be0e-9b68-4a97-bd38-09f2016303e6"
name = "Chinook (SQL Server)"

[environments.Build]
displayName = "Build Database"
provisioner = "backup"
url = "jdbc:sqlserver://localhost;databaseName=Chinook_Build;encrypt=mandatory;integratedSecurity=true;trustServerCertificate=true"

[environments.Build.resolvers.backup]
backupFilePath = "C:\\WorkingFolders\\FWD\\Chinook\\SqlServer\\migrations\\Chinook.bak"
backupVersion = "001"

  [environments.Build.resolvers.backup.sqlserver]
  generateWithMove = true

[environments.Check]
displayName = "Check Database"
provisioner = "backup"
url = "jdbc:sqlserver://localhost;databaseName=Chinook_Check;encrypt=mandatory;integratedSecurity=true;trustServerCertificate=true"

[environments.Check.resolvers.backup]
backupFilePath = "C:\\WorkingFolders\\FWD\\Chinook\\SqlServer\\migrations\\Chinook.bak"
backupVersion = "001"

  [environments.Check.resolvers.backup.sqlserver]
  generateWithMove = true

[environments.Prod]
url = "jdbc:sqlserver://127.0.0.1;authentication=sqlPassword;databaseName=Chinook_Prod;encrypt=mandatory;trustServerCertificate=true"
displayName = "Production Database"

[environments.Test]
displayName = "Test Database"
url = "jdbc:sqlserver://localhost;databaseName=Chinook_Test;encrypt=true;integratedSecurity=true;trustServerCertificate=true"

[environments.development]
url = "jdbc:sqlserver://127.0.0.1;authentication=sqlPassword;databaseName=Chinook_Dev;encrypt=true;trustServerCertificate=true"
displayName = "Development database"

[environments.shadow]
url = "jdbc:sqlserver://127.0.0.1;authentication=sqlPassword;databaseName=Chinook_Shadow;encrypt=mandatory;trustServerCertificate=true"
provisioner = "clean"

[flyway]
baselineOnMigrate = true
baselineVersion = "001_20260824093024"
callbackLocations = [ "filesystem:callbacks" ]
defaultSchema = "dbo"
errorOverrides = [ "S0001:0:I-" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  rulesConfig = ""
  rulesLocation = ""

[flyway.sqlserver.clean]
mode = "all"

[flywayDesktop]
enableMigrations = true
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = true

[redgateCompare]
filterFile = "filter.rgf"

  [[redgateCompare.staticDataTables]]
  schema = "dbo"
  table = "AppConfig"

  [redgateCompare.sqlserver]
  filterFile = "Filter.scpf"

[redgateCompare.sqlserver.options.behavior]
addCreateOrAlterForRerunnableScripts = false
addDropAndCreateForRerunnableScripts = false
addNoPopulationToFulltextIndexes = false
addObjectExistenceChecks = false
addOnlineOnWhenCreatingIndexesOrAlteringColumns = false
addWithEncryption = false
considerNextFilegroupInPartitionSchemes = true
decryptEncryptedObjects = true
disableAutoColumnMapping = false
dontUseAlterAssemblyToChangeClrObjects = false
forbidDuplicateTableStorageSettings = false
forceColumnOrder = false
ignoreMigrationScripts = false
includeDependencies = true
includeRoleExistenceChecks = true
includeSchemaExistenceChecks = true
inlineFulltextFields = false
inlineTableObjects = false
useCaseSensitiveObjectDefinition = false
useDatabaseCompatibilityLevel = false
useSetStatementsInScriptDatabaseInfo = false
writeAssembliesAsDlls = false

[redgateCompare.sqlserver.options.ignores]
ignoreAuthorizationOnSchemaObjects = false
ignoreBindings = false
ignoreChangeTracking = false
ignoreCollations = true
ignoreComments = false
ignoreDataCompression = true
ignoreDataSyncSchema = false
ignoreDatabaseAndServerNameInSynonyms = true
ignoreDmlTriggers = false
ignoreDynamicDataMasking = false
ignoreEventNotificationsOnQueues = false
ignoreExtendedProperties = false
ignoreFileGroupsPartitionSchemesAndPartitionFunctions = true
ignoreFillFactorAndIndexPadding = true
ignoreFullTextIndexing = false
ignoreIdentitySeedAndIncrementValues = false
ignoreIndexes = false
ignoreInsteadOfTriggers = false
ignoreInternallyUsedMicrosoftExtendedProperties = false
ignoreLockPropertiesOfIndexes = false
ignoreNocheckAndWithNocheck = false
ignoreNotForReplication = true
ignoreNullabilityOfColumns = false
ignorePerformanceIndexes = false
ignorePermissions = false
ignoreReplicationTriggers = true
ignoreSchemas = false
ignoreSensitivityClassifications = false
ignoreSetQuotedIdentifierAndSetAnsiNullsStatements = true
ignoreSquareBracketsInObjectNames = false
ignoreStatistics = true
ignoreStatisticsIncremental = false
ignoreStatisticsNoRecomputePropertyOnIndexes = false
ignoreSystemNamedConstraintAndIndexNames = false
ignoreTsqltFrameworkAndTests = true
ignoreUserProperties = true
ignoreUsersPermissionsAndRoleMemberships = true
ignoreWhiteSpace = true
ignoreWithElementOrder = true
ignoreWithEncryption = false
ignoreWithNoCheck = true

[redgateCompare.sqlserver.data.options.mapping]
includeTimestampColumns = false
useCaseSensitiveObjectDefinition = true

[redgateCompare.sqlserver.data.options.comparison]
compressTemporaryFiles = false
forceBinaryCollation = false
treatEmptyStringAsNull = false
trimTrailingWhiteSpace = false
useChecksumComparison = false
useMaxPrecisionForFloatComparison = false

[redgateCompare.sqlserver.data.options.deployment]
disableDdlTriggers = true
disableDmlTriggers = false
disableForeignKeys = false
dontIncludeCommentsInScript = false
dropPrimaryKeysIndexesAndUniqueConstraints = false
reseedIdentityColumns = false
skipIntegrityChecksForForeignKeys = false
transportClrDataTypesAsBinary = false
useExistenceChecks = false
